# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  push:
  pull_request:
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ( Build to ./dist or other directory... )
      - name: Install deno
        uses: denolib/setup-deno@master
      
 
      
      
      
      - name: Run cli
        run: |

          mkdir -p build
          mkdir book-fetch-action
          sudo apt install p7zip-full
          deno compile  -A  --unstable --target x86_64-unknown-linux-gnu --output build/book-fetch_x86_64_unknown_linux_gnu  main.js

          # strip build/book-fetch_x86_64_unknown_linux_gnu

          #gitaction使用
          cp build/book-fetch_x86_64_unknown_linux_gnu book-fetch-action/book-fetch_linux_gnu
          # deno compile  -A  --unstable --target x86_64-unknown-linux-gnu --output book-fetch-action/book-fetch_linux_gnu  main.js
          deno compile  -A  --unstable --target x86_64-unknown-linux-gnu --output book-fetch-action/uploadFiles_linux_gnu  uploadFiles.js
          # strip book-fetch-action/uploadFiles_linux_gnu
      
        
          deno compile  -A  --unstable --target aarch64-apple-darwin --output  build/book-fetch_aarch64_apple_darwin   main.js

    
        
          deno compile  -A  --unstable --target x86_64-apple-darwin --output  build/book-fetch_x86_64_apple_darwin   main.js

             
        
          deno compile  -A  --unstable --target x86_64-pc-windows-msvc --output   build/book-fetch_x86_64_windows_msvc.exe   main.js
          7z a -t7z -r ./build/book-fetch_x86_64_windows_msvc.7z ./build/book-fetch_x86_64_windows_msvc.exe

         
          
          7z a -t7z -r book-fetch-action.7z ./book-fetch-action/*
          mv  book-fetch-action.7z  ./build


       


      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './build'
          production-branch: master
          github-token: ${{ secrets.MY_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: 'nfp_ZrMJKZ7p7QHLFsY9zwVNx5o7Nb7PMoVqec86'
          NETLIFY_SITE_ID: '1c8a5176-b254-43af-ac7d-ff168942896d'
        timeout-minutes: 3


