# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  push:
  pull_request:
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ( Build to ./dist or other directory... )
      - name: Install deno
        uses: denolib/setup-deno@master
      
 
      
      
      
      - name: Run cli
        run: |

          mkdir build

          deno compile  -A --target x86_64-unknown-linux-gnu --output build/book-fetch_x86_64_unknown_linux_gnu  main.js
        
          deno compile  -A --target aarch64-apple-darwin --output  build/book-fetch_aarch64_apple_darwin   main.js
        
          deno compile  -A --target x86_64-apple-darwin --output  build/book-fetch_x86_64_apple_darwin   main.js
        
          deno compile  -A --target x86_64-pc-windows-msvc --output   build/book-fetch_x86_64_windows_msvc.exe   main.js

          

       


      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './build'
          production-branch: master
          github-token: ${{ secrets.MY_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: 'nfp_ZrMJKZ7p7QHLFsY9zwVNx5o7Nb7PMoVqec86'
          NETLIFY_SITE_ID: '128c385b-51d4-4034-938f-9172d978b238'
        timeout-minutes: 3


